// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvk-Z1c68Fu_tmxOrNp9GYB_EIA8lbbKA',
    appId: '1:844864161984:web:73be871d907976d3358525',
    messagingSenderId: '844864161984',
    projectId: 'maturitahelpdesk',
    authDomain: 'maturitahelpdesk.firebaseapp.com',
    storageBucket: 'maturitahelpdesk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2eSI56vrBn2bwueY4C7j0FO2PJht70g',
    appId: '1:844864161984:android:cee0e690437b8be3358525',
    messagingSenderId: '844864161984',
    projectId: 'maturitahelpdesk',
    storageBucket: 'maturitahelpdesk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE330NuEMQCvlnD0ddOKY69RGlPfR9LwE',
    appId: '1:844864161984:ios:704be0c65c826fb3358525',
    messagingSenderId: '844864161984',
    projectId: 'maturitahelpdesk',
    storageBucket: 'maturitahelpdesk.appspot.com',
    iosBundleId: 'com.example.maturitaHelpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE330NuEMQCvlnD0ddOKY69RGlPfR9LwE',
    appId: '1:844864161984:ios:3325c69317287ede358525',
    messagingSenderId: '844864161984',
    projectId: 'maturitahelpdesk',
    storageBucket: 'maturitahelpdesk.appspot.com',
    iosBundleId: 'com.example.maturitaHelpdesk.RunnerTests',
  );
}
